name: Create a comment on new issues workflow

on:
    issues:
        types: 
            - opened
            - closed
    
    workflow_dispatch:

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: dump github context
              run: echo '${{ toJson(github.event) }}' | jq
              shell: bash
